"""Доработки

Revision ID: ea6b2a47f772
Revises: bf9afd565b1e
Create Date: 2025-05-01 20:48:59.105631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea6b2a47f772'
down_revision = 'bf9afd565b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('table_type', sa.String(length=50), nullable=True),
    sa.Column('table_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_dashboard_id_fkey', 'dashboards', ['dashboard_id'], ['id'])
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('dashboard')

    op.create_table('dashboards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('table_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('table_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dashboards_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dashboards_pkey')
    )
    op.drop_table('dashboard')
    # ### end Alembic commands ###
